2차원 배열 행렬 예제입니다.

In [8]:
import numpy as np

def f(y, x):
   return 4*y + x + 1

a = np.fromfunction(f, (3, 4), dtype=int)

print( "*"*40 )
print(a)
print( "*"*40 )
print( a[ 1, 2 ] )
print( "*"*40 )
print( a[ 1, : ] )
print( "*"*40 )
print( a[ : , 2 ] )
print( "*"*40 )
print( a[:, 1:3] )
print( "*"*40 )
print( a[-2: , -2: ] )
print( "*"*40 )
print( a[ ::2, 1::2 ] )

****************************************
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
****************************************
7
****************************************
[5 6 7 8]
****************************************
[ 3  7 11]
****************************************
[[ 2  3]
 [ 6  7]
 [10 11]]
****************************************
[[ 7  8]
 [11 12]]
****************************************
[[ 2  4]
 [10 12]]


In [16]:
import numpy as np 

a = np.array( [ [1, 2, 3 ], [4, 5, 6] ] )

print( "a = ", a )
print( "sum = ", a.sum() )
print( "sum axis=0 = ", a.sum(axis=0) )
print( "sum axis=0 = ", a.sum(axis=1) )

a =  [[1 2 3]
 [4 5 6]]
sum =  21
sum axis=0 =  [5 7 9]
sum axis=0 =  [ 6 15]


In [27]:
import numpy as np 

a = np.array( [ 1, 2, 3 ] )
b = np.array( [ 1, 2, 3 ] )

print( "a = ", a )
print( "b = ", b )

print( "a@b = ", a@b )
print( "inner = ", np.dot(a, b) )
print( "outer = ", np.outer(a, b) )

a =  [1 2 3]
b =  [1 2 3]
a@b =  14
inner =  14
outer =  [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [8]:
import numpy as np
a = np.array( [ [8, 0, 0, 6], [1, 4, 3, 0], [0, 3, 1, 9] ] )

print( "a = ", a ) 
print( "a address = ", a.data )

b = a.reshape( 3, -1 )
print( "b = ", b )
print( "b address ", b.data )

a.resize( 2, 6 )
print( "a = ", a )
print( "a address = ", a.data )

a =  [[8 0 0 6]
 [1 4 3 0]
 [0 3 1 9]]
a address =  <memory at 0x00000149F31E4A00>
b =  [[8 0 0 6]
 [1 4 3 0]
 [0 3 1 9]]
b address  <memory at 0x00000149F31E4A00>
a =  [[8 0 0 6 1 4]
 [3 0 0 3 1 9]]
a address =  <memory at 0x00000149F31E4A00>
