In [10]:
import numpy as np

a = np.array( [ [4, 8, 5], [9, 3, 1] ] )

print( "a = ", a, "*"*30, sep="\n" )

print( "argmin() = ", a.argmin() )
print( "argmin(axis=0)", a.argmin(axis=0) )
print( "argmin(axis=1)", a.argmin(axis=1) )
print( "np.unravel_index(...) = ", np.unravel_index(a.argmin(), a.shape))
print( "np.unravel_index(...) = ", np.unravel_index(a.argmin(axis=0), a.shape))
print( "np.unravel_index(...) = ", np.unravel_index(a.argmin(axis=1), a.shape))

a = 
[[4 8 5]
 [9 3 1]]
******************************
argmin() =  5
argmin(axis=0) [0 1 1]
argmin(axis=1) [0 2]
np.unravel_index(...) =  (1, 2)
np.unravel_index(...) =  (array([0, 0, 0], dtype=int64), array([0, 1, 1], dtype=int64))
np.unravel_index(...) =  (array([0, 0], dtype=int64), array([0, 2], dtype=int64))


In [8]:
import numpy as np 

a = np.arange( 1, 7 ).reshape( 2, -1 )

print( "a = ", a, "*"*20, sep="\n" )
print( "np.any( a>5 )", np.any( a>5 ), "*"*20, sep="\n" )
print( "np.any( a>5, axis=0 )", np.any( a>5, axis=0 ), "*"*20, sep="\n" )
print( "np.any( a>5, axis=1 )", np.any( a>5, axis=1 ), "*"*20, sep="\n" )

a = 
[[1 2 3]
 [4 5 6]]
********************
np.any( a>5 )
True
********************
np.any( a>5, axis=0 )
[False False  True]
********************
np.any( a>5, axis=1 )
[False  True]
********************
