In [1]:
import numpy as np 

a = np.array( [ [4, 8, 5], [9, 3, 1] ] )

print( 'a = ', a, sep='\n' )
a.sort()
print( 'a.sort() = ', a, sep='\n' )

a = np.array( [ [4, 8, 5], [9, 3, 1] ] )
a.sort(axis=0)
print( 'a.sort(axis=0) = ', a, sep='\n' )

a = np.array( [ [4, 8, 5], [9, 3, 1] ] )
a.sort(axis=1)
print( 'a.sort(axis=1) = ', a, sep='\n' )

a = 
[[4 8 5]
 [9 3 1]]
a.sort() = 
[[4 5 8]
 [1 3 9]]
a.sort(axis=0) = 
[[4 3 1]
 [9 8 5]]
a.sort(axis=1) = 
[[4 5 8]
 [1 3 9]]


In [12]:
import numpy as np

a = np.array( [7, 4, 6, 5] )
b = np.argsort( a )
c = a[ b ]

print( 'a = ', a )
print( 'b = ', b )
print( 'c = ', c )

a = np.array( [ [7, 2, 9], [4, 3, 8],
               [6, 1, 7], [5, 0,4] ] 
             )
b = np.argsort( a[:, 0] )
c = a[ b ]
print( 'a = ', a, sep='\n' )
print( 'b = ', b )
print( 'c = ', c, sep='\n' )

a =  [7 4 6 5]
b =  [1 3 2 0]
c =  [4 5 6 7]
a = 
[[7 2 9]
 [4 3 8]
 [6 1 7]
 [5 0 4]]
b =  [1 3 2 0]
c = 
[[4 3 8]
 [5 0 4]
 [6 1 7]
 [7 2 9]]


In [4]:
import numpy as np

a = np.array( [ [1,5], [2, 7], [2, 6 ], [3, 4] ] )
aa = np.argsort( a[:,1] )
b = a[ aa ]
c = b[ np.argsort( b[:,0], kind='stable' ) ]

print( 'a = ', a , sep='\n' )
print( 'aa = ', aa , sep='\n' )
print( 'b = ', b , sep='\n' )
print( 'c = ', c , sep='\n' )

a = 
[[1 5]
 [2 7]
 [2 6]
 [3 4]]
aa = 
[3 0 2 1]
b = 
[[3 4]
 [1 5]
 [2 6]
 [2 7]]
c = 
[[1 5]
 [2 6]
 [2 7]
 [3 4]]


In [5]:
import numpy as np

a = np.array( [ [3,4], [2, 7], [1, 5], [2, 6] ] )
b = np.rot90(a)
c = np.lexsort( b )
d = a[c]

print( 'a = ', a , sep='\n' )
print( 'b = ', b , sep='\n' )
print( 'c = ', c , )
print( 'd = ', d , sep='\n' )

a = 
[[3 4]
 [2 7]
 [1 5]
 [2 6]]
b = 
[[4 7 5 6]
 [3 2 1 2]]
c =  [2 3 1 0]
d = 
[[1 5]
 [2 6]
 [2 7]
 [3 4]]
