In [1]:
import numpy as np
a = np.arange(1,16).reshape( -1, 5 )

print( "a = ", a, "*"*40, sep="\n")

# 상하좌우에 패딩 
b = np.pad( a, ( (0,1), (0, 0) ), constant_values=1)

print( "b = ", b, "*"*40, sep="\n")

# 상하좌우에 패딩 
c = np.pad( a, ( (0,0), (0, 2) ) )
print( "c = ", c, "*"*40, sep="\n")

# 상하좌우에 패딩 
d = np.pad( a, 1 )
print( "d = ", d, "*"*40, sep="\n")


a = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
****************************************
b = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  1  1  1  1]]
****************************************
c = 
[[ 1  2  3  4  5  0  0]
 [ 6  7  8  9 10  0  0]
 [11 12 13 14 15  0  0]]
****************************************
d = 
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]
****************************************


In [ ]:
# 메시 그리드 