In [8]:
import numpy as np 

a = np.array( [ [1, 2, 3 ], [4, 5, 6] ] )
b = np.array( [ [1, 2, 3 ] ] )
c = np.array( [1, 2, 3 ] )

print( "*"*40 )
print( "a.shape = ", a.shape )
print( "a = ", a )
print( "a.T = ", a.T )

print( "*"*40 )
print( "b.shape = ", b.shape )
print( "b = ", b )
print( "b.T = ", b.T )

print( "*"*40 )
print( "c.shape = ", c.shape )
print( "c = ", c )
print( "c.T = ", c.T )

****************************************
a.shape =  (2, 3)
a =  [[1 2 3]
 [4 5 6]]
a.T =  [[1 4]
 [2 5]
 [3 6]]
****************************************
b.shape =  (1, 3)
b =  [[1 2 3]]
b.T =  [[1]
 [2]
 [3]]
****************************************
c.shape =  (3,)
c =  [1 2 3]
c.T =  [1 2 3]


In [8]:
import numpy as np

a = np.array( [1, 2, 3] )
print( a.shape )
print( a )
print( "*"*40 )

r = a.reshape(1, -1)
print( r.shape )
print( r )
print( "*"*40 )

c = a.reshape( -1, 1 )
print( c.shape )
print( c )
print( "*"*40 )

(3,)
[1 2 3]
****************************************
(1, 3)
[[1 2 3]]
****************************************
(3, 1)
[[1]
 [2]
 [3]]
****************************************


In [20]:
import numpy as np

a = np.arange( 1, 13 ).reshape( -1, 4 )
b = np.arange( 1, 9 ).reshape( -1, 4 )
c = np.arange( 1, 7 ).reshape( -1, 2 )

d = np.vstack( (a,b) )
e = np.hstack( (a,c) )

print( "a = ", a, sep="\n" )
print( "*"*40 )
print( "b = ", b, sep="\n" )
print( "*"*40 )
print( "c = ", c, sep="\n" )
print( "*"*40 )

print( "d = ", d, sep="\n" )
print( "*"*40 )

print( "e = ", e, sep="\n" )
print( "*"*40 )


a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
****************************************
b = 
[[1 2 3 4]
 [5 6 7 8]]
****************************************
c = 
[[1 2]
 [3 4]
 [5 6]]
****************************************
d = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
****************************************
e = 
[[ 1  2  3  4  1  2]
 [ 5  6  7  8  3  4]
 [ 9 10 11 12  5  6]]
****************************************
