In [1]:
import numpy as np

# C 코딩 스타일
a = np.empty( (2, 3), np.int8 )
for i in range(2):
    for j in range(3) :
        a[i, j ] = j - i
    pass
pass

print( "a = ", a, "*"*40, sep="\n")

# 파이썬 코딩 스타일 
c = [ [(j-i) for j in range(3)] for i in range(2) ]
c = np.array( c, np.int8 )
print( "c = ", c, "*"*40, sep="\n")


a = 
[[ 0  1  2]
 [-1  0  1]]
****************************************
c = 
[[ 0  1  2]
 [-1  0  1]]
****************************************


In [16]:
import numpy as np

# Matlab 코딩 스타일
print( "Matlab 코딩 스타일" )
i, j = np.arange(2), np.arange(3)
i, j = np.meshgrid( i, j, indexing="ij" )
a = j - i 
print( "i = ", i, "*"*40, sep="\n")
print( "j = ", j, "*"*40, sep="\n")
print( "a = ", a, "*"*40, sep="\n")
print()

# 넘파이 코딩 스타일
print( "넘파이 코딩 스타일" )
i, j = np.arange(2), np.arange(3)
i, j = np.meshgrid( i, j, sparse=1, indexing="ij" )
a = j - i 
print( "i = ", i, "*"*40, sep="\n")
print( "j = ", j, "*"*40, sep="\n")
print( "a = ", a, "*"*40, sep="\n")

Matlab 코딩 스타일
i = 
[[0 0 0]
 [1 1 1]]
****************************************
j = 
[[0 1 2]
 [0 1 2]]
****************************************
a = 
[[ 0  1  2]
 [-1  0  1]]
****************************************

넘파이 코딩 스타일
i = 
[[0]
 [1]]
****************************************
j = 
[[0 1 2]]
****************************************
a = 
[[ 0  1  2]
 [-1  0  1]]
****************************************


In [6]:
import numpy as np

a = np.arange( 1, 5 ).reshape( -1, 2 )

I, J = np.indices( a.shape )

b = a[ I, J ]
c = a[ J, I ]

print( "a = ", a, "*"*40, sep="\n" )
print( "I = ", I, "*"*40, sep="\n" )
print( "J = ", J, "*"*40, sep="\n" )
print( "b = ", b, "*"*40, sep="\n" )
print( "c = ", c, "*"*40, sep="\n" )

a = 
[[1 2]
 [3 4]]
****************************************
I = 
[[0 0]
 [1 1]]
****************************************
J = 
[[0 1]
 [0 1]]
****************************************
b = 
[[1 2]
 [3 4]]
****************************************
c = 
[[1 3]
 [2 4]]
****************************************
